-- SYS 접속
connect sys/oracle as sysdba;
-- 계정 생성
CREATE USER MPJ_CURD IDENTIFIED BY admin1234;
-- 계정 권한 설정
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO MPJ_CURD IDENTIFIED BY admin1234;
ALTER USER MPJ_CURD DEFAULT TABLESPACE USERS;
ALTER USER MPJ_CURD TEMPORARY TABLESPACE TEMP;
-- 계정 접속
CONNECT MPJ_CURD/admin1234;
-- 시퀀스 생성
DROP SEQUENCE GAMEUSER_SEQ;
CREATE SEQUENCE GAMEUSER_SEQ
INCREMENT BY 1
START WITH 1;
-- 게임 유저 테이블 생성
DROP TABLE GAME_USER;
CREATE TABLE GAME_USER(
NO NUMBER(2) CONSTRAINT PK_GAMEUSER PRIMARY KEY,
IP VARCHAR2(15) NOT NULL,
NICKNAME VARCHAR2(10) NOT NULL,
SCORE NUMBER DEFAULT 0,
REGDATE DATE DEFAULT SYSDATE,
CONSTRAINT UQ_IP UNIQUE (IP),
CONSTRAINT UQ_NICKNAME UNIQUE (NICKNAME)
);
-- 데이터 추가
INSERT INTO GAME_USER(NO, IP, NICKNAME) VALUES(GAMEUSER_SEQ.NEXTVAL, '127.0.0.1', 'SCOTT'); 
-- 데이터 확인
SELECT * FROM GAME_USER;
-- 데이터 삭제
DELETE FROM GAME_USER;

commit

SELECT count(IP) FROM GAME_USER WHERE IP = '127.0.0.1';

-- 회원가입
CREATE OR REPLACE PROCEDURE SIGN_UP_GU(
	P_IP IN GAME_USER.IP%TYPE,
	P_NICKNAME IN GAME_USER.NICKNAME%TYPE)
IS
BEGIN
INSERT INTO GAME_USER(NO, IP, NICKNAME) VALUES(GAMEUSER_SEQ.NEXTVAL, P_IP, P_NICKNAME);
END;
/

BEGIN SIGN_UP_GU('127.0.0.1', 'SCOTT'); END;
/

-- 로그인 확인
CREATE OR REPLACE FUNCTION LOG_IN_GU(
	P_IP IN GAME_USER.IP%TYPE,
	P_NICKNAME IN GAME_USER.NICKNAME%TYPE)
RETURN NUMBER
IS
DBIP GAME_USER.IP%TYPE := NULL;
EXISTS_NUM NUMBER := 0;
BEGIN
SELECT CASE
WHEN EXISTS (SELECT NICKNAME FROM GAME_USER WHERE GAME_USER.NICKNAME = P_NICKNAME) THEN 1
ELSE 0
END
INTO EXISTS_NUM FROM DUAL;

IF EXISTS_NUM = 1 THEN
SELECT IP INTO DBIP
FROM GAME_USER
WHERE NICKNAME = P_NICKNAME;
IF DBIP = P_IP THEN
RETURN 1;
ELSE 
RETURN 0;
END IF;
ELSIF EXISTS_NUM = 0 THEN
RETURN 0;
END IF;
END;
/

CREATE OR REPLACE FUNCTION LOG_IN_GU(
	P_IP IN GAME_USER.IP%TYPE,
	P_NICKNAME IN GAME_USER.NICKNAME%TYPE)
RETURN NUMBER
IS
DBNICKNAME GAME_USER.NICKNAME%TYPE := NULL;
EXISTS_NUM NUMBER := 0;
BEGIN
SELECT CASE
WHEN EXISTS (SELECT IP FROM GAME_USER WHERE GAME_USER.IP = P_IP) THEN 1
ELSE 0
END
INTO EXISTS_NUM FROM DUAL;

IF EXISTS_NUM = 1 THEN
SELECT NICKNAME INTO DBNICKNAME
FROM GAME_USER
WHERE IP = P_IP;
IF DBNICKNAME = P_NICKNAME THEN
RETURN 1;
ELSE 
RETURN 0;
END IF;
ELSIF EXISTS_NUM = 0 THEN
RETURN 0;
END IF;
END;
/

{ ? = CALL LOG_IN_GU('127.0.0.1', 'SCOTT') }

variable res01 number;
execute :res01 := LOG_IN_GU('127.0.0.1', 'SCOTT');
print res01;
